### ISSUE TITLE
Missing Description under title

### ISSUE THREAD

**Issue by lfarah** [hyperoslo/OhMyAuth#8]
<img width="355" alt="screen shot 2016-02-17 at 5 20 44 pm" src="https://cloud.githubusercontent.com/assets/6511079/13130685/d5da9efe-d59a-11e5-9444-a95f7b17b060.png">
Should have this:

> Simple OAuth2 library with a support of multiple services.

**Comment by vadymmarkov** [comment]
@lfarah It's fixed now.

**Comment by lfarah** [comment]
Awesome 😄
